export type LocationType = "All" | "Origin" | "Destination" | "Bill to";

export type LocationAccessorial =
  | "Blind Shipment"
  | "Call Before Delivery"
  | "Call Before Pickup"
  | "Delivery Appointment"
  | "Guaranteed By 5PM"
  | "Inside Delivery"
  | "Inside Pick Up"
  | "Liftgate Delivery"
  | "Liftgate Pickup"
  | "Limited Access Delivery"
  | "Limited Access Pickup"
  | "Notify Before Delivery"
  | "Protect From Freeze"
  | "Residential Delivery"
  | "Residential Pick Up"
  | "Sort and Segregate"
  | "Trade Show Delivery"
  | "Trade Show Pickup"
  | "Hazmat"
  | "White Glove Service";

export interface CustomerLocation {
  key: string;
  locationName: string;
  shortName?: string;
  isActive: boolean;
  address1: string;
  address2: string;
  country: string;
  state: string;
  city: string;
  postal: string;
  contactName: string;
  phone: string;
  phoneExtension?: string;
  email: string;
  faxNumber?: string;
  activateDate: string;
  deactivateDate: string;
  group: string;
  locationType: LocationType;
  port?: string;
  locationRef?: string;
  inboundAccount?: string;
  outboundAccount?: string;
  notes?: string;
  openTime?: string;
  closeTime?: string;
  accessorials?: LocationAccessorial[];
}

export const customerLocationSeed: CustomerLocation[] = [
  {
    key: "loc-001",
    locationName: "ADVANCED INTERIORS",
    isActive: true,
    address1: "7287 GREENRIDGE RD",
    address2: "UNIT 1",
    country: "USA",
    state: "CO",
    city: "WINDSOR",
    postal: "80550",
    contactName: "RECEIVING",
    phone: "",
    email: "",
    activateDate: "12/4/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-002",
    locationName: "Anthropologie Direct KCI",
    isActive: true,
    address1: "11681 Sate Ave",
    address2: "",
    country: "USA",
    state: "KS",
    city: "KANSAS CITY",
    postal: "66111",
    contactName: "Receiving",
    phone: "5206335141",
    email: "",
    activateDate: "11/25/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-003",
    locationName: "Antilles Freight Forwarder",
    isActive: true,
    address1: "11206 NW 36th Street",
    address2: "",
    country: "USA",
    state: "FL",
    city: "MIAMI",
    postal: "33167",
    contactName: "Receiving",
    phone: "407-225-4137",
    email: "",
    activateDate: "12/8/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-004",
    locationName: "Attune Foods Eugene",
    isActive: true,
    address1: "2600 Prairie Rd",
    address2: "",
    country: "USA",
    state: "OR",
    city: "EUGENE",
    postal: "97402",
    contactName: "Receiver",
    phone: "541-743-9555",
    email: "",
    activateDate: "3/17/2026",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-005",
    locationName: "BGL",
    isActive: true,
    address1: "2046 S. Falkenburg Rd.",
    address2: "",
    country: "USA",
    state: "FL",
    city: "RIVERVIEW",
    postal: "33578",
    contactName: "",
    phone: "",
    email: "",
    activateDate: "3/1/2024",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Bill to",
  },
  {
    key: "loc-006",
    locationName: "BMA",
    isActive: true,
    address1: "1639 Rosecrans AVE",
    address2: "",
    country: "USA",
    state: "CA",
    city: "GARDENA",
    postal: "90249",
    contactName: "Melvin",
    phone: "323-682-3193",
    email: "",
    activateDate: "11/21/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-007",
    locationName: "BMA",
    isActive: true,
    address1: "1639 Rosecrans AVE",
    address2: "",
    country: "USA",
    state: "CA",
    city: "GARDENA",
    postal: "90249",
    contactName: "Shipping",
    phone: "323-682-3193",
    email: "",
    activateDate: "12/8/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Origin",
  },
  {
    key: "loc-008",
    locationName: "Double D Foods",
    isActive: true,
    address1: "113 D organ St",
    address2: "",
    country: "USA",
    state: "TX",
    city: "MERIDIAN",
    postal: "76665",
    contactName: "Veronica",
    phone: "254-435-6187",
    email: "",
    activateDate: "2/24/2026",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Destination",
  },
  {
    key: "loc-009",
    locationName: "ELEGANZA TILE",
    isActive: true,
    address1: "1061U TANNER RD",
    address2: "SUITE 100",
    country: "USA",
    state: "TX",
    city: "HOUSTON",
    postal: "77041",
    contactName: "SHIPPING",
    phone: "",
    email: "",
    activateDate: "12/4/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Origin",
  },
  {
    key: "loc-010",
    locationName: "Element chemicals",
    isActive: true,
    address1: "12936 FD 7U7 G",
    address2: "",
    country: "USA",
    state: "TX",
    city: "CLEVELAND",
    postal: "77327",
    contactName: "Guard Shack",
    phone: "352-250-5349",
    email: "",
    activateDate: "1/19/2026",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Origin",
  },
  {
    key: "loc-011",
    locationName: "Florida Tile Distribution",
    isActive: true,
    address1: "998 Governors Lane",
    address2: "Dock 4",
    country: "USA",
    state: "KY",
    city: "LEXINGTON",
    postal: "40513",
    contactName: "Logistics Desk",
    phone: "859-555-0112",
    email: "receiving@floridatile.example",
    activateDate: "1/5/2026",
    deactivateDate: "",
    group: "DISTRIBUTION",
    locationType: "Destination",
  },
  {
    key: "loc-012",
    locationName: "Georgia Pacific Atlanta",
    isActive: false,
    address1: "133 Peachtree Industrial Blvd",
    address2: "",
    country: "USA",
    state: "GA",
    city: "ATLANTA",
    postal: "30341",
    contactName: "Receiving Office",
    phone: "404-555-0198",
    email: "",
    activateDate: "6/12/2024",
    deactivateDate: "5/30/2026",
    group: "SOUTHEAST",
    locationType: "Destination",
  },
  {
    key: "loc-013",
    locationName: "Harbor Freight Services",
    isActive: true,
    address1: "4800 Port Road",
    address2: "Building C",
    country: "USA",
    state: "NJ",
    city: "NEWARK",
    postal: "07114",
    contactName: "Maria Santos",
    phone: "973-555-0160",
    email: "maria@harborfreight.example",
    activateDate: "4/18/2025",
    deactivateDate: "",
    group: "PORTS",
    locationType: "Origin",
  },
  {
    key: "loc-014",
    locationName: "Inland Transport Warehouse",
    isActive: true,
    address1: "4100 Commerce Drive",
    address2: "",
    country: "USA",
    state: "FL",
    city: "JACKSONVILLE",
    postal: "32218",
    contactName: "Dispatch",
    phone: "904-555-0128",
    email: "dispatch@inland.example",
    activateDate: "10/1/2023",
    deactivateDate: "",
    group: "INTERNAL",
    locationType: "Origin",
  },
  {
    key: "loc-015",
    locationName: "Jupiter Packaging",
    isActive: true,
    address1: "775 Innovation Way",
    address2: "Suite 210",
    country: "USA",
    state: "IL",
    city: "AURORA",
    postal: "60502",
    contactName: "Frank Miller",
    phone: "630-555-0144",
    email: "frank@jupiterpack.example",
    activateDate: "7/9/2025",
    deactivateDate: "",
    group: "STANDARD",
    locationType: "Bill to",
  },
  {
    key: "loc-016",
    locationName: "Keller Manufacturing",
    isActive: false,
    address1: "890 Industrial Park Rd",
    address2: "",
    country: "USA",
    state: "OH",
    city: "TOLEDO",
    postal: "43612",
    contactName: "Warehouse Team",
    phone: "419-555-0176",
    email: "",
    activateDate: "9/14/2023",
    deactivateDate: "2/28/2026",
    group: "MIDWEST",
    locationType: "Destination",
  },
  {
    key: "loc-017",
    locationName: "Liberty Cold Storage",
    isActive: true,
    address1: "250 Freezer Lane",
    address2: "Unit A",
    country: "USA",
    state: "PA",
    city: "PHILADELPHIA",
    postal: "19148",
    contactName: "Night Receiving",
    phone: "215-555-0183",
    email: "receiving@libertycold.example",
    activateDate: "8/22/2025",
    deactivateDate: "",
    group: "COLD CHAIN",
    locationType: "Destination",
  },
  {
    key: "loc-018",
    locationName: "Metro Supply Company",
    isActive: true,
    address1: "615 Market Street",
    address2: "",
    country: "USA",
    state: "TN",
    city: "NASHVILLE",
    postal: "37210",
    contactName: "Tanya Reed",
    phone: "615-555-0106",
    email: "tanya@metrosupply.example",
    activateDate: "3/11/2025",
    deactivateDate: "",
    group: "SOUTHEAST",
    locationType: "Bill to",
  },
  {
    key: "loc-019",
    locationName: "Northwest Consolidation",
    isActive: true,
    address1: "1440 Rivergate Blvd",
    address2: "Dock 12",
    country: "USA",
    state: "WA",
    city: "TACOMA",
    postal: "98421",
    contactName: "Inbound Team",
    phone: "253-555-0139",
    email: "inbound@nwconsolidation.example",
    activateDate: "12/16/2024",
    deactivateDate: "",
    group: "WEST COAST",
    locationType: "Origin",
  },
  {
    key: "loc-020",
    locationName: "Orlando Retail Center",
    isActive: true,
    address1: "8200 Orange Blossom Trail",
    address2: "",
    country: "USA",
    state: "FL",
    city: "ORLANDO",
    postal: "32809",
    contactName: "Receiving",
    phone: "407-555-0151",
    email: "orlando@retailcenter.example",
    activateDate: "5/6/2025",
    deactivateDate: "",
    group: "SOUTHEAST",
    locationType: "Destination",
  },
];

export const cloneCustomerLocationSeed = () =>
  customerLocationSeed.map((location) => ({ ...location }));
